version: "3.8"

services:
  auth-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app/main.py"
      FLASK_ENV: "development"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
