version: "3.9"
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://user:password@db:5432/userdb
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
